# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusiNess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='业务线')),
            ],
            options={
                'verbose_name_plural': '业务线',
            },
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=64, verbose_name='主机名')),
                ('idc', models.CharField(max_length=32, verbose_name='机房')),
                ('os', models.CharField(max_length=16, verbose_name='OS')),
                ('cpu', models.CharField(max_length=16, verbose_name='CPU')),
                ('mem', models.CharField(max_length=16, verbose_name='MEM')),
                ('disk', models.CharField(max_length=16, verbose_name='DISK')),
                ('status', models.CharField(max_length=16, verbose_name='状态')),
                ('owner', models.CharField(max_length=16, verbose_name='负责人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.BusiNess', verbose_name='所属业务线')),
            ],
            options={
                'verbose_name_plural': '主机表',
            },
        ),
    ]
